#!/usr/bin/env python3
"""anssi-s3-whitelist-update - refresh nftables IP whitelist sets from S3.

Downloads one or more whitelist files from a (private, encrypted) S3 bucket,
parses CIDR / IP lines, atomically writes a single nftables include file that
defines `s3_whitelist_v4` and `s3_whitelist_v6` sets, then validates the
resulting ruleset with `nft -c -f /etc/nftables.conf` and reloads nftables.

Configuration: /etc/anssi-s3-whitelist.yaml (see anssi-s3-whitelist.yaml.j2).
Credentials:   /etc/anssi-s3-whitelist.env (read by the systemd unit only).

Design rules:
  * No third-party deps beyond `awscli` (already required) and python3-yaml.
  * Atomic: writes to tmp, fsyncs, renames in place.
  * Fail-closed: on any error the previous include file is left untouched,
    nftables is NOT reloaded, exit != 0 (systemd picks it up as failed unit).
  * No silent expansion: lines that are not valid IPv4/IPv6 (host or CIDR)
    are logged and skipped, never injected into the ruleset.
"""

from __future__ import annotations

import argparse
import ipaddress
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Iterable

try:
    import yaml
except ImportError:  # pragma: no cover
    sys.stderr.write("python3-yaml is required\n")
    sys.exit(2)


DEFAULT_CONFIG = "/etc/anssi-s3-whitelist.yaml"
SET_NAME_V4 = "s3_whitelist_v4"
SET_NAME_V6 = "s3_whitelist_v6"


def _log(level: str, message: str) -> None:
    sys.stderr.write(f"[anssi-s3-whitelist] {level}: {message}\n")


def load_config(path: str) -> dict:
    with open(path, "r", encoding="utf-8") as fh:
        cfg = yaml.safe_load(fh) or {}
    required = ["bucket", "objects", "output_file"]
    missing = [k for k in required if k not in cfg]
    if missing:
        raise SystemExit(f"config missing keys: {missing}")
    return cfg


def aws_s3_download(
    bucket: str,
    key: str,
    dest: Path,
    region: str | None,
    endpoint_url: str | None,
    profile: str | None,
    extra_args: list[str] | None,
) -> None:
    """Download a single S3 object using awscli (uses ambient AWS_* env)."""
    if shutil.which("aws") is None:
        raise SystemExit("aws CLI is required (apt install awscli)")
    cmd: list[str] = ["aws", "s3api", "get-object", "--bucket", bucket, "--key", key, str(dest)]
    if region:
        cmd += ["--region", region]
    if endpoint_url:
        cmd += ["--endpoint-url", endpoint_url]
    if profile:
        cmd += ["--profile", profile]
    if extra_args:
        cmd += list(extra_args)
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        raise RuntimeError(
            f"s3 download failed for s3://{bucket}/{key}: "
            f"rc={result.returncode}, stderr={result.stderr.strip()}"
        )


def parse_lines(text: str) -> tuple[set[str], set[str], list[str]]:
    """Return (v4_set, v6_set, rejected_lines).

    Accepts host IPs (1.2.3.4, ::1) or CIDRs (1.2.3.0/24, 2001:db8::/32).
    Anything else (comment, blank, bad) is skipped or recorded as rejected.
    """
    v4: set[str] = set()
    v6: set[str] = set()
    rejected: list[str] = []
    for raw in text.splitlines():
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        token = line.split()[0]
        try:
            if "/" in token:
                net = ipaddress.ip_network(token, strict=False)
                {4: v4, 6: v6}[net.version].add(str(net))
            else:
                addr = ipaddress.ip_address(token)
                bits = 32 if addr.version == 4 else 128
                {4: v4, 6: v6}[addr.version].add(f"{addr}/{bits}")
        except ValueError:
            rejected.append(token)
    return v4, v6, rejected


def render_set(name: str, family: str, members: Iterable[str]) -> str:
    addr_type = "ipv4_addr" if family == "v4" else "ipv6_addr"
    body = [
        f"# Auto-generated by anssi-s3-whitelist-update for set {name}",
        f"# Members: {len(list(members))}",
        f"set {name} {{",
        f"    type {addr_type};",
        "    flags interval;",
        "    auto-merge;",
    ]
    sorted_members = sorted(set(members))
    if sorted_members:
        body.append("    elements = {")
        body.append(",\n".join(f"        {m}" for m in sorted_members))
        body.append("    }")
    body.append("}")
    return "\n".join(body) + "\n"


def atomic_write(path: Path, content: str, mode: int = 0o640) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp_fd, tmp_path = tempfile.mkstemp(prefix=".s3-whitelist-", dir=str(path.parent))
    try:
        with os.fdopen(tmp_fd, "w", encoding="utf-8") as fh:
            fh.write(content)
            fh.flush()
            os.fsync(fh.fileno())
        os.chmod(tmp_path, mode)
        os.replace(tmp_path, path)
    finally:
        if os.path.exists(tmp_path):
            try:
                os.unlink(tmp_path)
            except OSError:
                pass


def validate_and_reload(reload_cmd: list[str], main_config: str) -> None:
    check = subprocess.run(
        ["nft", "-c", "-f", main_config], capture_output=True, text=True
    )
    if check.returncode != 0:
        raise RuntimeError(f"nft -c failed: {check.stderr.strip()}")
    reload_res = subprocess.run(reload_cmd, capture_output=True, text=True)
    if reload_res.returncode != 0:
        raise RuntimeError(
            f"reload failed ({' '.join(reload_cmd)}): {reload_res.stderr.strip()}"
        )


def run(cfg: dict, apply: bool) -> int:
    bucket = cfg["bucket"]
    objects = cfg["objects"] or []
    output_file = Path(cfg["output_file"])
    main_config = cfg.get("nft_main_config", "/etc/nftables.conf")
    reload_cmd = cfg.get("reload_command", ["systemctl", "reload", "nftables"])

    v4: set[str] = set()
    v6: set[str] = set()
    rejected: list[str] = []

    with tempfile.TemporaryDirectory(prefix="anssi-s3-wl-") as tmpdir:
        for key in objects:
            local = Path(tmpdir) / Path(key).name
            aws_s3_download(
                bucket=bucket,
                key=key,
                dest=local,
                region=cfg.get("region"),
                endpoint_url=cfg.get("endpoint_url"),
                profile=cfg.get("profile"),
                extra_args=cfg.get("aws_cli_extra_args") or [],
            )
            text = local.read_text(encoding="utf-8", errors="replace")
            cur_v4, cur_v6, cur_rej = parse_lines(text)
            v4 |= cur_v4
            v6 |= cur_v6
            rejected.extend(cur_rej)

    if rejected:
        _log("warn", f"rejected {len(rejected)} invalid line(s) (first 5): {rejected[:5]}")

    content = (
        render_set(SET_NAME_V4, "v4", v4)
        + "\n"
        + render_set(SET_NAME_V6, "v6", v6)
    )
    atomic_write(output_file, content)

    _log("info", f"wrote {output_file} (v4={len(v4)}, v6={len(v6)})")
    if apply:
        validate_and_reload(reload_cmd, main_config)
        _log("info", "nftables reloaded")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description="Refresh nftables whitelist from S3.")
    parser.add_argument("--config", default=DEFAULT_CONFIG)
    parser.add_argument(
        "--apply",
        action="store_true",
        help="validate via `nft -c` and reload nftables when the include file changes",
    )
    args = parser.parse_args()
    try:
        cfg = load_config(args.config)
        return run(cfg, apply=args.apply)
    except (RuntimeError, OSError, SystemExit) as exc:
        _log("error", str(exc))
        return 1


if __name__ == "__main__":
    sys.exit(main())
